//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace ContentManagerMVC
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class dba2afc085e73f48c29d84a106000739c4Entities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new dba2afc085e73f48c29d84a106000739c4Entities1 object using the connection string found in the 'dba2afc085e73f48c29d84a106000739c4Entities1' section of the application configuration file.
        /// </summary>
        public dba2afc085e73f48c29d84a106000739c4Entities1() : base("name=dba2afc085e73f48c29d84a106000739c4Entities1", "dba2afc085e73f48c29d84a106000739c4Entities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dba2afc085e73f48c29d84a106000739c4Entities1 object.
        /// </summary>
        public dba2afc085e73f48c29d84a106000739c4Entities1(string connectionString) : base(connectionString, "dba2afc085e73f48c29d84a106000739c4Entities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dba2afc085e73f48c29d84a106000739c4Entities1 object.
        /// </summary>
        public dba2afc085e73f48c29d84a106000739c4Entities1(EntityConnection connection) : base(connection, "dba2afc085e73f48c29d84a106000739c4Entities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MediaPlayer> MediaPlayers
        {
            get
            {
                if ((_MediaPlayers == null))
                {
                    _MediaPlayers = base.CreateObjectSet<MediaPlayer>("MediaPlayers");
                }
                return _MediaPlayers;
            }
        }
        private ObjectSet<MediaPlayer> _MediaPlayers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PlayerSchedules> PlayerSchedules
        {
            get
            {
                if ((_PlayerSchedules == null))
                {
                    _PlayerSchedules = base.CreateObjectSet<PlayerSchedules>("PlayerSchedules");
                }
                return _PlayerSchedules;
            }
        }
        private ObjectSet<PlayerSchedules> _PlayerSchedules;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ScheduleContents> ScheduleContents
        {
            get
            {
                if ((_ScheduleContents == null))
                {
                    _ScheduleContents = base.CreateObjectSet<ScheduleContents>("ScheduleContents");
                }
                return _ScheduleContents;
            }
        }
        private ObjectSet<ScheduleContents> _ScheduleContents;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MediaPlayers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMediaPlayers(MediaPlayer mediaPlayer)
        {
            base.AddObject("MediaPlayers", mediaPlayer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PlayerSchedules EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPlayerSchedules(PlayerSchedules playerSchedules)
        {
            base.AddObject("PlayerSchedules", playerSchedules);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ScheduleContents EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToScheduleContents(ScheduleContents scheduleContents)
        {
            base.AddObject("ScheduleContents", scheduleContents);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dba2afc085e73f48c29d84a106000739c4Model", Name="MediaPlayer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MediaPlayer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MediaPlayer object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="iP">Initial value of the IP property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        public static MediaPlayer CreateMediaPlayer(global::System.Int32 id, global::System.String name, global::System.String iP, global::System.String status, global::System.String description)
        {
            MediaPlayer mediaPlayer = new MediaPlayer();
            mediaPlayer.Id = id;
            mediaPlayer.Name = name;
            mediaPlayer.IP = iP;
            mediaPlayer.Status = status;
            mediaPlayer.Description = description;
            return mediaPlayer;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IP
        {
            get
            {
                return _IP;
            }
            set
            {
                OnIPChanging(value);
                ReportPropertyChanging("IP");
                _IP = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IP");
                OnIPChanged();
            }
        }
        private global::System.String _IP;
        partial void OnIPChanging(global::System.String value);
        partial void OnIPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dba2afc085e73f48c29d84a106000739c4Model", Name="PlayerSchedules")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PlayerSchedules : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PlayerSchedules object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="startDateTime">Initial value of the StartDateTime property.</param>
        /// <param name="endDateTime">Initial value of the EndDateTime property.</param>
        /// <param name="continuious">Initial value of the Continuious property.</param>
        public static PlayerSchedules CreatePlayerSchedules(global::System.Int32 id, global::System.DateTime startDateTime, global::System.DateTime endDateTime, global::System.Boolean continuious)
        {
            PlayerSchedules playerSchedules = new PlayerSchedules();
            playerSchedules.Id = id;
            playerSchedules.StartDateTime = startDateTime;
            playerSchedules.EndDateTime = endDateTime;
            playerSchedules.Continuious = continuious;
            return playerSchedules;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime StartDateTime
        {
            get
            {
                return _StartDateTime;
            }
            set
            {
                OnStartDateTimeChanging(value);
                ReportPropertyChanging("StartDateTime");
                _StartDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartDateTime");
                OnStartDateTimeChanged();
            }
        }
        private global::System.DateTime _StartDateTime;
        partial void OnStartDateTimeChanging(global::System.DateTime value);
        partial void OnStartDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EndDateTime
        {
            get
            {
                return _EndDateTime;
            }
            set
            {
                OnEndDateTimeChanging(value);
                ReportPropertyChanging("EndDateTime");
                _EndDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndDateTime");
                OnEndDateTimeChanged();
            }
        }
        private global::System.DateTime _EndDateTime;
        partial void OnEndDateTimeChanging(global::System.DateTime value);
        partial void OnEndDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Continuious
        {
            get
            {
                return _Continuious;
            }
            set
            {
                OnContinuiousChanging(value);
                ReportPropertyChanging("Continuious");
                _Continuious = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Continuious");
                OnContinuiousChanged();
            }
        }
        private global::System.Boolean _Continuious;
        partial void OnContinuiousChanging(global::System.Boolean value);
        partial void OnContinuiousChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dba2afc085e73f48c29d84a106000739c4Model", Name="ScheduleContents")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ScheduleContents : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ScheduleContents object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static ScheduleContents CreateScheduleContents(global::System.Int32 id, global::System.String name)
        {
            ScheduleContents scheduleContents = new ScheduleContents();
            scheduleContents.Id = id;
            scheduleContents.Name = name;
            return scheduleContents;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
    }

    #endregion
    
}
