// <auto-generated />
namespace ContentManagerMVC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class WCFsettings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WCFsettings));
        
        string IMigrationMetadata.Id
        {
            get { return "201212090012554_WCFsettings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
