// <auto-generated />
namespace ContentManagerMVC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class add_lists2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_lists2));
        
        string IMigrationMetadata.Id
        {
            get { return "201211180107067_add_lists2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
