// <auto-generated />
namespace ContentManagerMVC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class new25 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new25));
        
        string IMigrationMetadata.Id
        {
            get { return "201211190720257_new25"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
