// <auto-generated />
namespace ContentManagerMVC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _new : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_new));
        
        string IMigrationMetadata.Id
        {
            get { return "201211120517166_new"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
